version: 2

updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 0
    rebase-strategy: 'auto'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Europe/Madrid'
    versioning-strategy: 'increase'
    open-pull-requests-limit: 20
    rebase-strategy: 'auto'
    groups:
      dev-deps:
        dependency-type: 'development'
    allow:
      - dependency-type: 'direct'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: 'monthly'
